GitInitTest/GitInitTest.Site/ViewModels/AdminPwResetViewModel.cs
using GitInitTest.Entities.Dtos;
using GitInitTest.Entities.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.AccessControl;
using System.Threading.Tasks;

namespace GitInitTest.Site.ViewModels
{
    public class AdminPwResetViewModel : BaseViewModel
    {
        public AdminPwResetViewModel()
        {
        }

        public AdminPwResetViewModel(string userName)
        {
            UserName = userName;
        }

        public string UserName { get; set; }
        public string Password { get; set; }
    }
}

GitInitTest/GitInitTest.Site/Controllers/UserInformationAdminController.cs
using GitInitTest.Entities.Dtos;
using GitInitTest.Entities.Models;
using GitInitTest.Site.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Threading.Tasks;

namespace GitInitTest.Site.Controllers
{
    //[Authorize(Roles = "Administrator")]
    public class UserInformationAdminController : Controller
    {
        private readonly IUserInformationAdminService _service;

        public UserInformationAdminController(IUserInformationAdminService userInformationAdminService)
        {
            _service = userInformationAdminService;
        }

        // GET: UserInformationAdmin
        //public async Task<IActionResult> Index([Bind("LastName")]UserSearchDto userSearchDto)
        //{
        //    if (userSearchDto == null) userSearchDto = new UserSearchDto();

        //    //Todo: make the service methods asynchronous
        //    var userView = _userInformationAdminService.GetIndexView(userSearchDto);
        //    return View(userView);
        //}

        [HttpPost, HttpGet]
        public async Task<IActionResult> Index(
            [Bind("LastName")] UserInformationAdminSearchDto searchDto = null,
            [Bind("SortOrder,CurrentSort,CurrentFilter,SearchString,IncludedProperties,Page,PageNumber,PageSize")] PageListActionDto pageListActionDto = null,
            Guid? id = null)
        {
            var viewModel = await
                _service.GetIndexViewAsync(searchDto, pageListActionDto, id);

            return View(viewModel);
        }

        //public async Task<IActionResult> Index(
        //    [Bind("CiShortDesc,CiActive,CiDeleted,CId,parm_ShortDescSort,parm_DescSort")] CompanySearchDto ciCatalogItemSearchDto = null,
        //    [Bind("SortOrder,CurrentSort,CurrentFilter,SearchString,IncludedProperties,Page,PageNumber,PageSize")] PageListActionDto pageListActionDto = null)
        //{
        //    var viewModel = await
        //        _service.GetIndexViewAsync(ciCatalogItemSearchDto, pageListActionDto);

        //    return View(viewModel);
        //}

        // GET: UserInformationAdmin/Create
        public IActionResult Create()
        {
            var createView = _service.GetCreateView();
            return View(createView);
        }

        // POST: UserInformationAdmin/Create
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Create([Bind("CompanyId,FirstName,LastName,Email,Enabled")] User userInformation, string[] selectedUserRoles)
        //{
        //    if (userInformation.Email != null && _userInformationAdminService.CheckUser(userInformation.Email))
        //    {
        //        ModelState.AddModelError("LanId", "LanId Already Exists");
        //    }

        //    if (ModelState.IsValid)
        //    {
        //        _userInformationAdminService.CreateUser(userInformation, selectedUserRoles);

        //        return RedirectToAction(nameof(Index));
        //    }
        //    var createView = _userInformationAdminService.GetEditView(userInformation, selectedUserRoles, "Create User");
        //    return View(createView);
        //}

        // GET: UserInformationAdmin/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var editView = await _service.GetEditViewAsync(id, "Edit User");

            return View(editView);
        }

        //POST: UserInformationAdmin/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UserName,FirstName,LastName,Email,PhoneNumber,Password,ConfirmPassword,IsEnabled,EmailConfirmed")] RegisterUserDto userInformation, string[] selectedUserRoles)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    //_context.Update(userInformation);
                    //await _context.SaveChangesAsync();
                    await _service.CreateUserAsync(userInformation, selectedUserRoles);
                }
                catch (DbUpdateConcurrencyException)
                {
                    throw;
                }
                return RedirectToAction(nameof(Index));
            }

            var editView = _service.GetEditView(new ApplicationUser(userInformation), "Create User");
            return View(editView);
        }

        //POST: UserInformationAdmin/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("UserName,FirstName,LastName,Email,PhoneNumber,IsEnabled,EmailConfirmed")] ApplicationUser userInformation, string[] selectedUserRoles)
        {
            if (id != userInformation.UserName)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    //_context.Update(userInformation);
                    //await _context.SaveChangesAsync();
                    await _service.UpdateUserAsync(userInformation, selectedUserRoles);
                }
                catch (DbUpdateConcurrencyException)
                {
                    throw;
                }
                return RedirectToAction(nameof(Index));
            }
            var editView = _service.GetEditView(userInformation, "Edit User");
            return View(editView);
        }

        // GET: UserInformationAdmin/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var editView = await _service.GetEditViewAsync(id, "Delete User");

            return View(editView);
        }

        // POST: UserInformationAdmin/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            await _service.DeleteUser(id);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult AdminPwReset(string id)
        {
            var adminPwResetView = _service.GetAdminPwResetView(id);
            return View(adminPwResetView);
        }

        // POST: UserInformationAdmin/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AdminPwReset([Bind("UserName,Password")] AdminPwResetDto adminPwResetDto)
        {
            if (ModelState.IsValid)
            {
                await _service.AdminPwReset(adminPwResetDto);

                return RedirectToAction(nameof(Index));
            }
            var adminPwResetView = _service.GetAdminPwResetView(adminPwResetDto.UserName);
            return View(adminPwResetView);
        }
    }
}

GitInitTest/GitInitTest.Site/Views/UserInformationAdmin/AdminPwReset.cshtml
@model AdminPwResetViewModel

<h1>Reset</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AdminPwReset">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<input type="hidden" asp-for="UserName" value="@Model.UserName" />*@
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GitInitTest/GitInitTest.Site/Views/UserInformationAdmin/Create.cshtml
@model UserInfoAdminEditViewModel

<div class="col-md-6 offset-3">
    <div class="card card-default">
        <div class="card-header text-center"><h4>@Model.Title</h4></div>

        @if (ViewBag.Message != null)
        {
            <p class="alert-danger text-center">@ViewBag.Message</p>
            <br />
        }
        <div class="card-body">
            <form asp-action="Create" id="editForm">
                <input type="hidden" name="IsSendToUser" id="IsSendToUser" value="false" />
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="row">
                    <div class="col-6">
                        <div class="form-group">
                            <label asp-for="UserInformation.UserName" class="control-label"></label>
                            <input asp-for="UserInformation.UserName" id="UserName" class="form-control" />
                            <span asp-validation-for="UserInformation.UserName" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-6">
                    </div>
                </div>
                <div class="row">
                    <div class="col-6">
                        <div class="form-group">
                            <label asp-for="UserInformation.FirstName" class="control-label"></label>
                            <input asp-for="UserInformation.FirstName" id="FirstName" class="form-control" />
                            <span asp-validation-for="UserInformation.FirstName" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            <label asp-for="UserInformation.LastName" class="control-label"></label>
                            <input asp-for="UserInformation.LastName" id="LastName" class="form-control" />
                            <span asp-validation-for="UserInformation.LastName" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                

                <div class="form-group">
                    <label asp-for="UserInformation.Email" class="control-label"></label>
                    <input asp-for="UserInformation.Email" id="Email" class="form-control" />
                    <span asp-validation-for="UserInformation.Email" class="text-danger"></span>
                </div>
                <div class="row">
                    <div class="col-6">
                        <div class="form-group">
                            <label asp-for="UserInformation.Password"></label>
                            <input asp-for="UserInformation.Password" class="form-control" />
                            <span asp-validation-for="UserInformation.Password" class="text-danger"></span>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-6">
                        <div class="form-group">
                            <label asp-for="UserInformation.ConfirmPassword"></label>
                            <input asp-for="UserInformation.ConfirmPassword" class="form-control" />
                            <span asp-validation-for="UserInformation.ConfirmPassword" class="text-danger"></span>
                        </div>
                    </div>
                </div>

                <div class="form-group ">
                    <div class="checkbox">
                        <label>
                            <input id="Enabled" asp-for="UserInformation.IsEnabled" /> @Html.DisplayNameFor(model => model.UserInformation.IsEnabled)
                        </label>
                    </div>
                    <div class="checkbox">
                        <label>
                            <input id="Enabled" asp-for="UserInformation.EmailConfirmed" /> @Html.DisplayNameFor(model => model.UserInformation.EmailConfirmed)
                        </label>
                    </div>
                </div>
                <hr />

                <label>Roles</label>
                <div class="row">
                    @{
                        int cnt = 0;
                        foreach (var userRole in Model.AssignedRoleDatas)
                        {
                            if (cnt++ % 3 == 0)
                            {

                            @:</div><div class="row">

                            }

                            <div class="col-md-4">

                                <input type="checkbox"
                                       name="selectedUserRoles"
                                       value="@userRole.Name"
                                       @(Html.Raw(userRole.Assigned ? "checked=\"checked\"" : "")) />
                                @userRole.Name
                            </div>

                        }
                    }
                </div>
                <hr />
                <div class="row">

                    <div class="col-md-6"><a asp-action="Index" class="btn btn-block btn-outline-danger"><span class="fa fa-times"></span> Cancel</a></div>

                    <div class="col-md-6"><a href='#' id="editFormSubmit" class="btn btn-block btn-outline-primary"><span class="fa fa-check"></span> Save</a></div>
                </div>
            </form>
        </div>
        <div class="card-footer">
            <a href='javascript:window.history.back();'>Back to List</a>
        </div>
    </div>
</div>

<!-- Lookup User Modal -->


@{await Html.RenderPartialAsync("_NotifyUserYesNoModal");}

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <environment include="Development">
        <script src="~/js/PageScripts/UserInformationEdit.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/js/PageScripts/UserInformationEdit-min.js" asp-append-version="true"></script>
    </environment>
}

GitInitTest/GitInitTest.Site/Views/UserInformationAdmin/Delete.cshtml
@model UserInfoAdminEditViewModel

@{
    ViewData["Title"] = Model.Title;
}

<div class="row">
    <div class="col-md-4 offset-4">
        <div class="card border-danger">
            <div class="card-header text-center bg-danger text-white"><h4>@Model.Title</h4></div>

            <div class="card-body bg-light">

                @if (Model.Message != null)
                {
                    <p class="alert-danger text-center">@Model.Message</p>
                }

                <dl>

                    <dt>
                        @Html.DisplayNameFor(model => model.UserInformation.FirstName)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.UserInformation.FirstName)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.UserInformation.LastName)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.UserInformation.LastName)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.UserInformation.Email)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.UserInformation.Email)
                    </dd>
                    
                </dl>
                <hr />
                <label>Roles</label>
                <div class="row">
                    @{
                        int cnt = 0;
                        foreach (var userRole in Model.AssignedRoleDatas)
                        {
                            if (cnt++ % 2 == 0)
                            {

                            @:</div><div class="row">

                            }

                            <div class="col-md-6">

                                <input type="checkbox"
                                       name="selectedUserRoles"
                                       value="@userRole.UserRoleId"
                                       @(Html.Raw(userRole.Assigned ? "checked=\"checked\"" : "")) disabled />
                                @userRole.Name
                            </div>

                        }
                    }
                </div>
                <hr />
                <div class="text-center">
                    <form asp-action="Delete">
                        <input type="hidden" asp-for="UserInformation.Id" />
                        <input type="submit" value="Delete" class="btn btn-outline-danger" />
                    </form>
                </div>
            </div>
            <div class="card-footer bg-danger">
                <a class="text-white" href='javascript:window.history.back();'>Back to List</a>
            </div>
        </div>
    </div>
</div>

GitInitTest/GitInitTest.Site/Views/UserInformationAdmin/Edit.cshtml
@model UserInfoAdminEditViewModel

@{
    ViewData["Title"] = Model.Title;
}
<div class="row">
    <div class="col-md-6 offset-3">
        <div class="card card-default">
            <div class="card-header text-center"><h4>@Model.Title</h4></div>

            @if (Model.Message != null)
            {
                <p class="alert-danger text-center">@Model.Message</p>
            }

            <div class="card-body">
                <form asp-action="Edit"  id="editForm">

                    <div asp-validation-summary="All" class="text-danger"></div>
                    <input type="hidden" asp-for="UserInformation.UserName" name="id" />
                    <input type="hidden" name="IsSendToUser" id="IsSendToUser" value="false" />
                    <div class="form-group">
                        <label asp-for="UserInformation.UserName" class="control-label"></label>
                        <input asp-for="UserInformation.UserName" class="form-control" readonly />
                        <span asp-validation-for="UserInformation.UserName" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="UserInformation.FirstName" class="control-label"></label>
                        <input asp-for="UserInformation.FirstName" class="form-control" />
                        <span asp-validation-for="UserInformation.FirstName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="UserInformation.LastName" class="control-label"></label>
                        <input asp-for="UserInformation.LastName" class="form-control" />
                        <span asp-validation-for="UserInformation.LastName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="UserInformation.Email" class="control-label"></label>
                        <input asp-for="UserInformation.Email" class="form-control" />
                        <span asp-validation-for="UserInformation.Email" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="UserInformation.PhoneNumber" class="control-label"></label>
                        <input asp-for="UserInformation.PhoneNumber" class="form-control" />
                        <span asp-validation-for="UserInformation.PhoneNumber" class="text-danger"></span>
                    </div>

                    <div class="form-group ">
                        <div class="checkbox">
                            <label>
                                <input id="Enabled" asp-for="UserInformation.IsEnabled" /> @Html.DisplayNameFor(model => model.UserInformation.IsEnabled)
                            </label>
                        </div>
                        <div class="checkbox">
                            <label>
                                <input id="Enabled" asp-for="UserInformation.EmailConfirmed" /> @Html.DisplayNameFor(model => model.UserInformation.EmailConfirmed)
                            </label>
                        </div>
                    </div>
                    <hr />
                    <label>Roles</label>
                    <div class="row">
                        @{
                            int cnt = 0;
                            foreach (var userRole in Model.AssignedRoleDatas)
                            {
                                if (cnt++ % 3 == 0)
                                {

                                @:</div><div class="row">




                                }

                                <div class="col-md-4">

                                    <input type="checkbox"
                                           name="selectedUserRoles"
                                           value="@userRole.Name"
                                           @(Html.Raw(userRole.Assigned ? "checked=\"checked\"" : "")) />
                                    @userRole.Name
                                </div>

                            }
                        }
                    </div>
                    <hr />
                    <hr />
                    <div class="row">

                        <div class="col-md-6"><a asp-controller="UserInformationAdmin" asp-action="Index" class="btn btn-block btn-outline-danger"><span class="fa fa-times"></span> Cancel</a></div>

                        <div class="col-md-6"><a href='#' id="editFormSubmit" class="btn btn-block btn-outline-primary"><span class="fa fa-check"></span> Save</a></div>
                    </div>
                    @*<div class="form-group text-center">
                        <input type="submit" value="Save" class="btn btn-outline-primary" />
                        <a href='javascript:window.history.back();' class="btn btn-outline-danger">Cancel</a>
                    </div>*@
                </form>
            </div>
            <div class="card-footer">
                <a href='javascript:window.history.back();'>Back to List</a>
            </div>
        </div>
    </div>
</div>

<!-- NotifyUserYesNoModal User Modal -->
@{await Html.RenderPartialAsync("_NotifyUserYesNoModal");}

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <environment include="Development">
        <script src="~/js/PageScripts/UserInformationEdit.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/js/PageScripts/UserInformationEdit-min.js" asp-append-version="true"></script>
    </environment>
}

GitInitTest/GitInitTest.Site/Views/UserInformationAdmin/Index.cshtml
@using X.PagedList.Mvc.Core
@using X.PagedList.Mvc.Core.Common
@model UserInfoAdminIndexViewModel

<div class="col-md-8 offset-2">
    <div class="card card-default">
        <div class="card-header">
            <div class="row">
                <div class="col-md-4 pull-left">
                </div>
                <div class="col-md-4  text-center">
                    <h3>@Model.Title</h3>
                </div>
                <div class="col-md-4 text-right">
                    <div>
                        <a asp-area="" asp-controller="UserInformationAdmin" asp-action="Create" class="btn btn-outline-primary">Create New User</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-body">

            <div class="pull-left">

                <form method="get" asp-action="index" id="indexForm" class="form-inline">
                    <input type="hidden" name="currentFilter" id="currentFilter" asp-for="PageListAction.CurrentFilter" />
                    <input type="hidden" name="sortOrder" id="sortOrder" asp-for="PageListAction.CurrentFilter" />
                    <input type="hidden" name="id" id="id" />

                    <p>
                        <input asp-for="SearchDto.LastName" id="LastName" name="LastName" class="form-control" placeholder="Find by last name" />
                        <!--Buttons have to be anchors or the jQuery submit wont work-->
                        <a value="Search" id="search" class="btn btn-outline-secondary">Search</a>
                        <a value="Reset" id="reset" class="btn btn-outline-secondary">Reset</a>
                        (use '*' for a wildcard search)
                    </p>
                </form>
            </div>
        </div>
        <div class="table-responsive">
            <table class="table table-bordered table-hover tableFixHead">
                <tr>
                    <th>
                        <a class="sortColumn" href="#" data-value="@Model.SortDto.UserName">User Id</a>
                    </th>

                    <th>
                        <a class="sortColumn" href="#" data-value="@Model.SortDto.FirstName">First Name</a>
                    </th>
                    <th>
                        <a class="sortColumn" href="#" data-value="@Model.SortDto.LastName">Last Name</a>
                    </th>
                    <th>
                        Email
                    </th>
                    <th>
                    </th>
                </tr>

                @foreach (var item in Model.UserInformations)
                {
                    string selectedRow = "";
                    if (item.Id == Model.SelectedUserInformation?.Id)
                    {
                        selectedRow = "bg-info";
                    }
            <tr class="@selectedRow">
                <td>
                    @Html.DisplayFor(modelItem => item.UserName)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>

                    <a class="select" href="#" data-value="@item.Id">Select</a> |
                    <a asp-area="" asp-controller="UserInformationAdmin" asp-action="Edit" asp-route-id="@item.UserName">Edit</a> |
                    <a asp-area="" asp-controller="UserInformationAdmin" asp-action="Delete" asp-route-id="@item.UserName">Delete</a>
                </td>
            </tr>

                }
            </table>
        </div>

        @*</div>*@
        <div class="card-footer text-center">

            <div class="text-center">
                Page @(Model.UserInformations.PageCount < Model.UserInformations.PageNumber ? 0 : Model.UserInformations.PageNumber) of @Model.UserInformations.PageCount
            </div>
            <div>

                @Html.PagedListPager(Model.UserInformations, page => Url.Action("Index",
                    new
                    {
                        VName = Model.SearchDto.LastName,
                        id = "",
                        page = page,
                        sortOrder = Model.PageListAction.CurrentSort,
                        currentFilter = Model.PageListAction.CurrentFilter
                    }), new PagedListRenderOptions
                    {
                        UlElementClasses = new string[] { "pagination justify-content-center" },
                        LiElementClasses = new string[] { "page-item" },
                        PageClasses = new string[] { "page-link" }
                    })
            </div>

            <div class="text-left"><a asp-controller="Admin" asp-action="Index">Back</a></div>
            <div class="clearfix"></div>
        </div>
    </div>
    <div class="clearfix"></div>
    <br /><br />
</div>
<div class="clearfix"></div>

<!-- User Information Detail Modal -->
@{await Html.RenderPartialAsync("_UserInformationModal");}

@section Head
{
    <environment include="Development">
        <link rel="stylesheet" href="~/css/PageStyles/tableFixedHeader.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/css/PageStyles/tableFixedHeader.min.css" asp-append-version="true" />
    </environment>
}

@section Scripts
{
    <environment include="Development">
        <script src="~/js/PageScripts/UserInformationIndex.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/js/PageScripts/UserInformationIndex-min.js" asp-append-version="true"></script>
    </environment>
}

GitInitTest/GitInitTest.Site/Views/UserInformationAdmin/_NotifyUserYesNoModal.cshtml
<div class="modal fade" id="notifyYesNoModal" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header bg-dark">

                <h5 class="modal-title text-white">Notify User</h5>
                <button type="button" class="close text-white cuClose" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <div class="modal-body">
                <p>Would you like to notify the user that their ID has been approved?</p>
            </div>
            <div class="modal-footer">
                <button id="sendToUser" class="btn btn-outline-primary">Yes</button>
                <button type="submit" id="idSearchModalCancel" class="btn btn-outline-danger" data-dismiss="modal">No</button>
            </div>
        </div>
    </div>
</div>